language: node_js
node_js:
  - '8'
dist: trusty
env:
  - NODE_ENV = 'ci'
cache:
  directories:
    - node_modules
install:
  - npm install
scripts:
  - nohup npm run start &
  - sleep 5
  - npm run test
